# Advanced Python Programming (APP)
## Course Code (CC) - CSI - 3007
### Laboratory (Lab)
#### Digital Assignment - 03

## Working On NumPy Arrays In Advanced Python Programming Lab
### Custom User Own Client Customer Individual Synthetic Dataset  
#### Python Programming Coding Scripting Computer Science Language
#### Jupyter Notebook Core Main Crux Framework Library Module Binary Package  

# Working On NumPy Arrays In Advanced Python Programming Lab
## Student: Dharshan Raj P A
## Register Roll Number ID: 22MIC0073
## Date: 12-09-2025

# WORKING ON NUMPY ARRAYS.

# ARRAY() METHOD

In [1]:
import numpy as np
ArrayTwoD = np.array([[9, 8, 7], [6, 5, 4]])  # Create A 2D Array
print(ArrayTwoD)

[[9 8 7]
 [6 5 4]]


# ARRAY ATTRIBUTES

In [2]:
print(ArrayTwoD.size)  # Number Of Elements

6


In [3]:
print(ArrayTwoD.shape)  # Rows And Columns (Shape)

(2, 3)


In [4]:
print(ArrayTwoD.ndim)  # Number Of Dimensions

2


# RESHAPE METHOD

In [5]:
LinearArray = np.array([9, 8, 7, 6, 5, 4])
print("Original Array:", LinearArray)
print("Original Shape:", LinearArray.shape)

Original Array: [9 8 7 6 5 4]
Original Shape: (6,)


In [6]:
# Reshape To A 2D Array (2 Rows, 3 Columns)
ReshapedArray = LinearArray.reshape(2, 3)  # Reshape 1D Array To 2D Array
print(ReshapedArray)
print("New Shape:", ReshapedArray.shape)

[[9 8 7]
 [6 5 4]]
New Shape: (2, 3)


# ARRANGE METHOD

In [7]:
def NumpySum(NumElements):
  Squares = np.arange(NumElements) ** 2  # [0..N-1] Squared Element Wise
  Cubes = np.arange(NumElements) ** 3
  Total = Squares + Cubes                # Element Wise Addition (No Python Loops)
  return Total

NumpySum(10)

array([  0,   2,  12,  36,  80, 150, 252, 392, 576, 810])

# ARRAY CREATION FUNCTION

In [8]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [10]:
np.arange(2, 3, 0.05)  # Step Value Is 0.05

array([2.  , 2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ,
       2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95])

# ARRAY METHOD

In [11]:
ArrayA = np.array([1, 2, 3, 4, 5, 6])
print(ArrayA)

[1 2 3 4 5 6]


In [12]:
MatrixB = np.array([[1, 2], [3, 4]])
print(MatrixB)

[[1 2]
 [3 4]]


In [13]:
# In NumPy, The Fundamental Array Object Is An Ndarray.
TensorC = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(TensorC)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# DTYPE ATTRIBUTE

In [14]:
np.array([127, 128, 129], dtype=np.int32)

array([127, 128, 129], dtype=int32)

In [15]:
# Demonstration Of Int8 Overflow Behavior When Casting Out Of Bound Values
np.array([127, 128, 129], dtype=np.int8)

OverflowError: Python integer 128 out of bounds for int8

# LINSPACE METHOD

In [16]:
# The Interval Is Divided Into 5 Equal Steps (6 Points Define 5 Intervals).
np.linspace(1.0, 4.0, 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

# EYE METHOD IN NUMPY

In [17]:
# Identity Matrix Of Shape 4x4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
# Matrix With Ones On The Main Diagonal (Shape 4x6)
np.eye(4, 6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

In [19]:
# Optional K Shifts The Diagonal: Negative → Below Main Diagonal, Positive → Above
np.eye(4, 6, k=-4)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
np.eye(3, 5, k=2)  # Positive K Places The Diagonal Above The Main Diagonal

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# DIAG METHOD

In [21]:
# Build A Diagonal Matrix From A 1D Array
np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [22]:
# Upper Diagonal (K=1) In A Square Matrix Of Size (N + K)
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [23]:
MatrixA = np.array([[1, 2], [3, 4]])
np.diag(MatrixA)

array([1, 4])

# VANDERMONDE MATRIX

In [24]:
# N = 2 → Two Columns: X**1, X**0
np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [25]:
# np.vander(X, N) Creates A Vandermonde Matrix From A 1D Input Array X.
# [[X1**(N-1), X1**(N-2), ..., X1**0],
#  [X2**(N-1), X2**(N-2), ..., X2**0],
#  ...
#  [Xn**(N-1), Xn**(N-2), ..., Xn**0]]
# Each Row Lists Decreasing Powers Of An Element From X.

In [26]:
np.vander([1, 2, 3, 4], 2)  # Creates A 4x2 Matrix

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [27]:
np.vander((1, 2, 3, 4), 4)  # Creates A 4x4 Matrix

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [28]:
np.vander((1, 2, 3, 4), 3)  # Each Row Is [X**2, X, 1] For Each X In The Input

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

# ONES METHOD

In [29]:
OnesArray1D = np.ones(5)  # Shape=5 (1D), Default Dtype=Float
print("1D Array Of Ones:", OnesArray1D)

1D Array Of Ones: [1. 1. 1. 1. 1.]


In [30]:
OnesMatrix2D = np.ones((3, 4))  # Shape=(3, 4) → 3x4 Matrix
print("\n2D Array (3x4) Of Ones:\n", OnesMatrix2D)


2D Array (3x4) Of Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
OnesMatrixInt = np.ones((2, 3), dtype=int)  # Shape=(2, 3), Dtype=Int
print("\n2D Integer Array (2x3) Of Ones:\n", OnesMatrixInt)


2D Integer Array (2x3) Of Ones:
 [[1 1 1]
 [1 1 1]]


In [32]:
OnesArray3D = np.ones((2, 2, 3))  # Shape=(2, 2, 3) → 3D Array
print("\n3D Array Of Ones:\n", OnesArray3D)


3D Array Of Ones:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [33]:
OnesBooleanMatrix = np.ones((3, 3), dtype=bool)
print("\nBoolean Array (3x3) Of Ones (True Values):\n", OnesBooleanMatrix)


Boolean Array (3x3) Of Ones (True Values):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


# ZEROS METHOD

In [34]:
ZerosArray1D = np.zeros(5)  # Shape=5 (1D), Default Dtype=Float
print("1D Array Of Zeros:", ZerosArray1D)

1D Array Of Zeros: [0. 0. 0. 0. 0.]


In [35]:
ZerosMatrix2D = np.zeros((3, 4))  # Shape=(3, 4) → 3x4 Matrix
print("\n2D Array (3x4) Of Zeros:\n", ZerosMatrix2D)


2D Array (3x4) Of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [36]:
ZerosMatrixInt = np.zeros((2, 3), dtype=int)  # Shape=(2, 3), Dtype=Int
print("\n2D Integer Array (2x3) Of Zeros:\n", ZerosMatrixInt)


2D Integer Array (2x3) Of Zeros:
 [[0 0 0]
 [0 0 0]]


In [37]:
ZerosArray3D = np.zeros((2, 2, 3))  # Shape=(2, 2, 3) → 3D Array
print("\n3D Array Of Zeros:\n", ZerosArray3D)


3D Array Of Zeros:
 [[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


# INDICES METHOD

In [38]:
IndicesGrid3x3 = np.indices((3, 3))  # 3 Rows And 3 Columns
print("Indices For A 3x3 Grid:\n", IndicesGrid3x3)

Indices For A 3x3 Grid:
 [[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


In [39]:
print("\nRow Indices (First Array):\n", IndicesGrid3x3[0])


Row Indices (First Array):
 [[0 0 0]
 [1 1 1]
 [2 2 2]]


In [40]:
print("\nColumn Indices (Second Array):\n", IndicesGrid3x3[1])


Column Indices (Second Array):
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


In [41]:
IndicesGrid2x4 = np.indices((2, 4))
print("\nIndices For A 2x4 Grid:\n", IndicesGrid2x4)


Indices For A 2x4 Grid:
 [[[0 0 0 0]
  [1 1 1 1]]

 [[0 1 2 3]
  [0 1 2 3]]]


In [42]:
print("\nRow Indices:\n", IndicesGrid2x4[0])


Row Indices:
 [[0 0 0 0]
 [1 1 1 1]]


In [43]:
print("\nColumn Indices:\n", IndicesGrid2x4[1])


Column Indices:
 [[0 1 2 3]
 [0 1 2 3]]


# RANDOM METHOD

In [44]:
RandomFloat = np.random.random()
print("Random Float (0 To 1):", RandomFloat)

Random Float (0 To 1): 0.7690245054618696


In [45]:
RandomArray1D = np.random.random(5)
print("\n1D Array Of Random Floats:", RandomArray1D)


1D Array Of Random Floats: [0.19135328 0.81197094 0.06953308 0.41573659 0.24266518]


In [46]:
RandomMatrix3x3 = np.random.random((3, 3))
print("\n2D Array (3x3) Of Random Floats:\n", RandomMatrix3x3)


2D Array (3x3) Of Random Floats:
 [[0.81743391 0.01788876 0.08123118]
 [0.21453236 0.43572155 0.70042963]
 [0.13067079 0.93926787 0.28932884]]


In [47]:
RandomIntegers = np.random.randint(10, 50, size=5)
print("\nRandom Integers Between 10 And 50:", RandomIntegers)


Random Integers Between 10 And 50: [22 26 16 11 35]


In [48]:
RandomNormal = np.random.randn(4)
print("\nRandom Numbers From Normal Distribution:", RandomNormal)


Random Numbers From Normal Distribution: [ 0.66183047 -0.11075168 -0.81113059 -1.35784338]


# SLICING AND INDEXING IN ARRAYS

In [49]:
Numbers1D = np.array([50, 60, 70, 80, 90, 100])
print("1D Array:", Numbers1D)

1D Array: [ 50  60  70  80  90 100]


In [50]:
print("\nIndexing On 1D Array:")
print("Element At Index 0:", Numbers1D[0])   # First Element
print("Element At Index -1:", Numbers1D[-1]) # Last Element


Indexing On 1D Array:
Element At Index 0: 50
Element At Index -1: 100


In [51]:
print("\nSlicing On 1D Array:")
print("Elements From Index 1 To 4:", Numbers1D[1:5])  # From Index 1 Up To 4
print("Every Second Element:", Numbers1D[::2])        # Step Of 2
print("Reverse Array:", Numbers1D[::-1])


Slicing On 1D Array:
Elements From Index 1 To 4: [60 70 80 90]
Every Second Element: [50 70 90]
Reverse Array: [100  90  80  70  60  50]


In [52]:
# Create A 2D Array (3x4 Matrix)
Numbers2D = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]])
print("\n2D Array:\n", Numbers2D)


2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
print("\nIndexing On 2D Array:")
print("Element At Row 1, Column 2:", Numbers2D[1, 2])   # 7 (Row=1, Col=2)
print("First Row:", Numbers2D[0])                      # Whole First Row
print("First Column:", Numbers2D[:, 0])


Indexing On 2D Array:
Element At Row 1, Column 2: 7
First Row: [1 2 3 4]
First Column: [1 5 9]
